#!/usr/bin/env ruby

Dir.chdir __dir__ do
    require 'bundler/setup'
    require 'require_all'
    require 'colorize'
    require 'docopt'
end

require_rel 'lib'

require 'securerandom'
require 'shellwords'
require 'tempfile'
require 'open3'
require 'etc'

class Enparallel
    def self.run(cli)
        tasks = TaskList.new(cli.targets, cli.command, cli.pick)
        new(tasks).run
    end

    def initialize(tasks)
        @tasks = tasks
    end

    def run
        # @tasks.start

        # render_progress do
        #     @tasks.execute
        # end

        # @tasks.finish
    end

    private

    def render_progress
        thread = Thread.new { loop { render } }
        yield
        thread.terminate
        render
        puts
    end

    def render
        print "\r" + @tasks.render
        sleep 0.1
    end
end

Enparallel.run(CLI.parse(ARGV))
